#!/usr/bin/env bash
: ${TRY5_STORE_PATH:=/tmp/try5.db}
: ${TRY5_STORE_TIMEOUT:=10}
: ${TRY5_PORT:=9000}
: ${TRY5_VERBOSE:=true}
: ${TRY5_SSLCERT:=certs/cert.pem}
: ${TRY5_SSLKEY:=certs/key.pem}

clear
TRY5_STORE_PATH=${TRY5_STORE_PATH} TRY5_STORE_TIMEOUT=${TRY5_STORE_TIMEOUT} TRY5_PORT=${TRY5_PORT} TRY5_VERBOSE=${TRY5_VERBOSE} TRY5_SSLCERT=${TRY5_SSLCERT} TRY5_SSLKEY=${TRY5_SSLKEY} go run *.go
