#!/usr/bin/env bash
: ${TRY5_STORE_PORT:=49163}
: ${TRY5_PORT:=8000}
: ${TRY5_VERBOSE:=debug}
: ${TRY5_STORE_HOST:=b2d}
: ${TRY5_STORE_NAME:=insdb}
: ${TRY5_STORE_USER:=insadmin}
: ${TRY5_STORE_PASS:=00000000}
: ${LOGXI:=*}

clear
TRY5_STORE_PORT=${TRY5_STORE_PORT} TRY5_PORT=${TRY5_PORT} TRY5_VERBOSE=${TRY5_VERBOSE} TRY5_STORE_HOST=${TRY5_STORE_HOST} TRY5_STORE_NAME=${TRY5_STORE_NAME} TRY5_STORE_USER=${TRY5_STORE_USER} TRY5_STORE_PASS=${TRY5_STORE_PASS} LOGXI=${LOGXI} go run *.go
